const WA="966574203528";
const dict={
ar:{
navServices:"الخدمات",navHow:"كيف يعمل",navProviders:"مقدمو الخدمات",navFaq:"الأسئلة",navCta:"اطلب خدمة",eyebrow:"● خدمة محلية بأسلوب أبسط",heroTitle:"تحتاج خدمة؟ <em>تمام.</em>",heroText:"أرسل احتياجك عبر واتساب، ونرتب لك الوصول إلى مقدم خدمة مناسب. بدون خطوات معقدة.",start:"ابدأ طلبك ←",explore:"استكشف الخدمات",trustFree:"مجاني للعميل",trustDirect:"تواصل مباشر",trustNoPay:"الدفع لمقدم الخدمة",floatReceived:"تم استلام الطلب",floatDirect:"تواصل مباشر",scroll:"مرّر",
servicesKicker:"خدمات اليوم",servicesTitle:"وش تحتاج؟ <em>تمام موجود.</em>",servicesText:"نبدأ بالخدمات اليومية الأكثر طلبًا، ونوسعها تدريجيًا.",sMove:"نقل العفش",sMoveText:"نقل وترتيب العفش داخل جدة.",sUsed:"أثاث مستعمل",sUsedText:"بيع، شراء، ونقل الأثاث.",sClean:"تنظيف",sCleanText:"تنظيف المنازل والمساحات.",sHome:"خدمات منزلية",sHomeText:"صيانة ومهام منزلية متنوعة.",sOther:"خدمة أخرى",sOtherText:"قل لنا وش تحتاج ونشوف لك.",soon:"قريبًا",sHousing:"السكن والغرف",sHousingText:"قسم قادم ضمن خطة التوسع.",
howKicker:"بكل بساطة",howTitle:"من الطلب إلى الخدمة<br><em>بأربع خطوات.</em>",step1:"أرسل طلبك",step1t:"اكتب لنا الخدمة التي تحتاجها وموقعك وموعدك.",step2:"نبحث لك",step2t:"نرتب الخيارات من مقدمي الخدمات المناسبين.",step3:"اختر وتواصل",step3t:"بعد موافقتك، يتواصل معك مقدم الخدمة.",step4:"قيّم تجربتك",step4t:"شاركنا تقييمك بعد انتهاء الخدمة.",
providerKicker:"لمقدمي الخدمات",providerTitle:"عندك خدمة تقدمها؟<br><em>خل العملاء يوصلون لك.</em>",providerText:"تعرف على طريقة التسجيل وآلية استقبال الطلبات في صفحة مخصصة لمقدمي الخدمات.",providerBtn:"سجّل كمقدم خدمة ←",
faqKicker:"الأسئلة الشائعة",faqTitle:"قبل ما تبدأ،<br><em>خلّنا نوضح.</em>",faq1:"هل استخدام تمام مجاني للعميل؟",faq1t:"نعم، طلب الخدمة عبر تمام مجاني للعميل في هذه المرحلة.",faq2:"هل أدفع لتمام أو لمقدم الخدمة؟",faq2t:"تمام لا يحتفظ بمبلغ الخدمة. الدفع للخدمة يكون مباشرة مع مقدم الخدمة.",faq3:"متى يتم مشاركة رقمي؟",faq3t:"بعد اختيارك وموافقتك على مشاركة رقمك مع مقدم الخدمة.",
ctaKicker:"جاهز؟",ctaTitle:"قل لنا وش تحتاج.<br><em>والباقي علينا.</em>",ctaBtn:"ابدأ عبر واتساب ←",footerText:"خدمات محلية، بطريقة أبسط.",privacy:"الخصوصية",terms:"الشروط",footerLocation:"جدة، المملكة العربية السعودية",
pEyebrow:"صفحة مقدمي الخدمات",pTitle:"عندك مهارة أو خدمة؟<br><em>خل تمام يعرّف العملاء عليك.</em>",pText:"سجّل اهتمامك، أرسل بياناتك الأساسية عبر واتساب، وبعدها نرتب معك الخطوة التالية.",pCta:"سجّل اهتمامك كمقدم خدمة ←",pTrust:"التسجيل يبدأ من واتساب",pMini:"طلبات جديدة تبدأ من هنا",pHowKicker:"كيف تبدأ؟",pHowTitle:"ثلاث خطوات، <em>وبس.</em>",pStep1:"أرسل اهتمامك",pStep1t:"اضغط الزر وارسل الرسالة الجاهزة في واتساب.",pStep2:"أرسل معلوماتك",pStep2t:"نوع الخدمة، المدينة، ووسيلة التواصل المناسبة.",pStep3:"نتابع معك",pStep3t:"نراجع البيانات ونوضح لك الخطوة التالية قبل أي اتفاق.",pNoteTitle:"واضحة من البداية",pNoteText:"تمام لا يحتفظ بمبلغ الخدمة. تفاصيل السعر والتنفيذ والدفع تكون مباشرة بين العميل ومقدم الخدمة.",pCtaKicker:"جاهز تبدأ؟",pCtaTitle:"أرسل كلمة واحدة.<br><em>ونبدأ.</em>",pCtaBottom:"سجّل اهتمامك عبر واتساب ←",backHome:"← العودة للموقع",
legalPrivacyTitle:"سياسة الخصوصية",legalPrivacyText:"نستخدم البيانات التي ترسلها عبر قنوات تمام لمعالجة طلب الخدمة والتواصل بشأنه. لا نشارك رقمك مع مقدم الخدمة إلا بعد موافقتك. لا نطلب بيانات دفع عبر الموقع.",legalContact:"للاستفسارات، تواصل معنا عبر واتساب تمام.",legalTermsTitle:"الشروط والأحكام",legalTermsText:"تمام منصة لتسهيل الوصول إلى مقدمي الخدمات. الاتفاق على السعر ونطاق الخدمة والتنفيذ يكون مباشرة بين العميل ومقدم الخدمة.",legalTermsText2:"تمام لا يحتفظ بمبالغ الخدمة ولا يضمن جودة أو نتيجة أي خدمة مقدمة من طرف ثالث، وعلى العميل التحقق من التفاصيل قبل الاتفاق."
},
en:{
navServices:"Services",navHow:"How it works",navProviders:"Service providers",navFaq:"FAQ",navCta:"Request a service",eyebrow:"● Local services, made simpler",heroTitle:"Need a service? <em>TAMAM.</em>",heroText:"Send your request on WhatsApp and we’ll help you reach a suitable service provider. No complicated steps.",start:"Start your request →",explore:"Explore services",trustFree:"Free for customers",trustDirect:"Direct contact",trustNoPay:"Pay the provider",floatReceived:"Request received",floatDirect:"Direct contact",scroll:"Scroll",
servicesKicker:"Services today",servicesTitle:"What do you need? <em>TAMAM is here.</em>",servicesText:"We start with everyday services and expand step by step.",sMove:"Moving",sMoveText:"Furniture moving and arranging in Jeddah.",sUsed:"Used furniture",sUsedText:"Buy, sell, and move used furniture.",sClean:"Cleaning",sCleanText:"Home and space cleaning.",sHome:"Home services",sHomeText:"Maintenance and everyday home tasks.",sOther:"Other service",sOtherText:"Tell us what you need and we’ll check.",soon:"Coming soon",sHousing:"Housing & rooms",sHousingText:"A future section in our expansion plan.",
howKicker:"Simple by design",howTitle:"From request to service<br><em>in four steps.</em>",step1:"Send your request",step1t:"Tell us the service, location, and preferred time.",step2:"We look for options",step2t:"We organize suitable provider options for you.",step3:"Choose & connect",step3t:"After your approval, the provider contacts you.",step4:"Rate your experience",step4t:"Share your feedback after the service.",
providerKicker:"For service providers",providerTitle:"Offer a service?<br><em>Let customers find you.</em>",providerText:"Learn how to register and how service requests work on a dedicated provider page.",providerBtn:"Join as a provider →",
faqKicker:"Frequently asked",faqTitle:"Before you start,<br><em>let’s make it clear.</em>",faq1:"Is TAMAM free for customers?",faq1t:"Yes. Customer service requests through TAMAM are free at this stage.",faq2:"Do I pay TAMAM or the provider?",faq2t:"TAMAM does not hold the service payment. Payment is made directly to the provider.",faq3:"When is my phone number shared?",faq3t:"Only after you choose a provider and agree to share your number.",
ctaKicker:"Ready?",ctaTitle:"Tell us what you need.<br><em>We’ll take it from there.</em>",ctaBtn:"Start on WhatsApp →",footerText:"Local services, made simpler.",privacy:"Privacy",terms:"Terms",footerLocation:"Jeddah, Saudi Arabia",
pEyebrow:"Service provider page",pTitle:"Have a skill or service?<br><em>Let TAMAM introduce you to customers.</em>",pText:"Register your interest, send your basic details on WhatsApp, and we’ll guide you through the next step.",pCta:"Register your interest →",pTrust:"Registration starts on WhatsApp",pMini:"New requests start here",pHowKicker:"How to start",pHowTitle:"Three steps, <em>that’s it.</em>",pStep1:"Send your interest",pStep1t:"Tap the button and send the ready-made WhatsApp message.",pStep2:"Send your details",pStep2t:"Service type, city, and your preferred contact method.",pStep3:"We follow up",pStep3t:"We review the details and explain the next step before any agreement.",pNoteTitle:"Clear from the start",pNoteText:"TAMAM does not hold the service payment. Price, execution, and payment details are agreed directly between customer and provider.",pCtaKicker:"Ready to start?",pCtaTitle:"Send one message.<br><em>Let’s begin.</em>",pCtaBottom:"Register via WhatsApp →",backHome:"← Back to website",
legalPrivacyTitle:"Privacy Policy",legalPrivacyText:"We use the information you send through TAMAM channels to process service requests and communicate about them. We only share your phone number with a provider after you agree. We do not request payment details on the website.",legalContact:"For questions, contact TAMAM through WhatsApp.",legalTermsTitle:"Terms & Conditions",legalTermsText:"TAMAM helps customers reach service providers. Price, scope, and execution are agreed directly between the customer and provider.",legalTermsText2:"TAMAM does not hold service payments or guarantee third-party service quality or outcomes. Customers should verify the details before agreeing."
}};
let lang=localStorage.getItem("tamam-lang")||"ar";
function applyLang(){
const d=dict[lang];document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";
document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(d[k]!==undefined)el.innerHTML=d[k]});
const toggle=document.getElementById("langToggle");if(toggle)toggle.textContent=lang==="ar"?"EN":"AR";
document.title=lang==="ar"?(document.body.dataset.page==="providers"?"مقدمو الخدمات | تمام TAMAM":document.body.dataset.page==="legal"?"تمام | الخصوصية والشروط":"تمام | TAMAM"):"TAMAM | Local services";
bindWhatsApp();
}
function bindWhatsApp(){
document.querySelectorAll("[data-wa]").forEach(a=>{
const type=a.dataset.wa,service=a.dataset.service;let msg;
if(type==="provider")msg=lang==="ar"?"مرحبًا تمام، أبغى أسجل اهتمامي معكم كمقدم خدمة. أبغى أعرف الخطوات والمتطلبات.":"Hi TAMAM, I’d like to register my interest as a service provider. Please share the steps and requirements.";
else if(service)msg=lang==="ar"?"مرحبًا تمام، أحتاج خدمة: "+service+". أبغى أرسل لكم تفاصيل الطلب.":"Hi TAMAM, I need this service: "+service+". I’d like to send you the request details.";
else msg=lang==="ar"?"مرحبًا تمام، أحتاج خدمة وأبغى أرسل تفاصيل الطلب.":"Hi TAMAM, I need a service and would like to send the request details.";
a.href="https://wa.me/"+WA+"?text="+encodeURIComponent(msg);a.target="_blank";a.rel="noopener";
});
}
document.addEventListener("DOMContentLoaded",()=>{
applyLang();const toggle=document.getElementById("langToggle");if(toggle)toggle.addEventListener("click",()=>{lang=lang==="ar"?"en":"ar";localStorage.setItem("tamam-lang",lang);applyLang()});
const year=document.getElementById("year");if(year)year.textContent=new Date().getFullYear();
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");observer.unobserve(e.target)}}),{threshold:.12});
document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
});